sudo: false
language: python
cache:
- pip
install:
- pip install -r requirements.txt
- pip install -e .
script:
- echo 'Nada!'
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: __token__
  password: ${TOKEN}
  skip_existing: true